### ISSUE TITLE
"Far cry"

### ISSUE THREAD

**Issue by xinyazhang** [tycheng/PlanetRenderer#12]
Texture is missing for distanced terrain.
![screen shot 2015-04-07 at 5 14 02 pm](https://cloud.githubusercontent.com/assets/11429462/7035023/63ead2f8-dd4a-11e4-963f-e627033a39d6.png)

**Comment by tycheng** [comment]
I tested with static camera, and it works without this. Currently I am not sure about the reason, but I could try changing camera frustum and see if it has anything to do with that.

**Comment by tycheng** [comment]
I played with terrain generation a little bit, and discover that if I turn terrain's generation criteria of "far" to different fixed values, the results are different.
1. If far == 1024, there is no such problem indicated, yet some terrains are "shaking" by a little bit while moving.
2. If far == 2048, most of the time it is the same as far == 1024 situation, but sometimes it shows the texture problem.
3. If far == 4096 or more, such problem begins to show more often.

**Comment by xinyazhang** [comment]
Linear Z solves this.
