### ISSUE TITLE
Terrain morphed vertex position

### ISSUE THREAD

**Issue by tycheng** [tycheng/PlanetRenderer#13]
Currently the vertices of the terrain patches are not connected seamlessly. Seams appear during the borders of terrain patches. To avoid this, we need to have a morphVertex function, and also computeMorphK function. 

Currently morphVertex is implemented, but computeMorphK is not implemented correctly.

**Comment by tycheng** [comment]
I have been trying some time but it seems that I am not able to fix the seam at this point. In the CDLOD paper, the seam was fixed by morphVertex (we have that already). However, the essential thing, morphK (the amount for the vertex to morph) is ambiguous in the paper. I have been trying for some hours, but it does not seem to work well.

**Comment by xinyazhang** [comment]
I don't think we really need this feature (i.e. seamless multiple-patch rendering)
We can use single patch with different density of vertices to achieve similar effects.

**Comment by tycheng** [comment]
Well, whatever that works will be fine for me. The point is to get rid of the seams around the boundary of a patch. We can discuss more about it.
