### ISSUE TITLE
Trees: with actual polygons or just billboard?

### ISSUE THREAD

**Issue by tycheng** [tycheng/PlanetRenderer#20]
1. Do we need to make trees?
2. Do we actually create polygons for tree or we just make billboards of tree?

**Comment by xinyazhang** [comment]
I think we need trees, but with minimum efforts.

**Comment by tycheng** [comment]
Billboard will be the very minimal effort, but billboard looks cheap. That is why I am hesitating.

**Comment by xinyazhang** [comment]
It's ok as long as we (the camera) don't jump into the forest.
