### ISSUE TITLE
Things remaining to be done

### ISSUE THREAD

**Issue by tycheng** [tycheng/PlanetRenderer#21]
- [x] integration of macro hierarchical tiling
- [x] iteration of day and night
- [ ] optimization for billboard grass/tree (botany)
- [ ] shadow mapping
- [ ] Terrain camera collision detection
- [ ] hdr illuminated sky?
- [x] FFT (gerstner) waves
- [ ] fix seams on LOD terrain (if possible)?
- [x] Terrain Generation

**Comment by xinyazhang** [comment]
This should be a milestone with those issues attached

**Comment by xinyazhang** [comment]
- [x] Terrain Generation

**Comment by xinyazhang** [comment]
Terrain camera collision detection should be done after using Tiling System.
