### ISSUE TITLE
Clean up GLSL

### ISSUE THREAD

**Issue by xinyazhang** [tycheng/PlanetRenderer#8]
1. Ensure no DOS style line breaks.
2. Ensure no texture2D in all GLSL code. OS X does not support this.

**Comment by tycheng** [comment]
Last time when I pulled, I got vertex shader with MSDOS style line breaks. I did not delete those because I though that was okay for compilation.

**Comment by tycheng** [comment]
What does OS X support for texture?

**Comment by xinyazhang** [comment]
OSX only supports overloaded texture in GLSL, instead of texture1/2/3D
Linux is more flexible, although I believe it's only because they reused old compiler to parse GLSL.

**Comment by xinyazhang** [comment]
Check this highlighter https://github.com/beyondmarc/glsl.vim.
It marks legacy keywords in a different color.

**Comment by tycheng** [comment]
Okay, thank.
