### ISSUE TITLE
set fixed fps for update and rendering

### ISSUE THREAD

**Issue by tycheng** [tycheng/PlanetRenderer#9]
Drawing more than 30 frames per second is wasteful because human eyes are indifferent to high frame rate and lower ones as long as they do not look laggy. We could try to fix the frame rate and have it as an option.

I wonder if this is something available in Qt quick, or do we have to manually encode that?

**Comment by xinyazhang** [comment]
We can do vsync and I think we already had it. But in general I'm against this idea after we achieved tearing free by nature.

First, with vsync we won't have any idea about the actual performance until we noticed the FPS dropped a half.

Second, human eyes are able to recognize far more than 30 frames. In fact, Edison recommended 48 frames. "30 FPS is enough" are no more than commercial words trying to persuade consumers "we're not so bad in technology."

Xinya

**Comment by tycheng** [comment]
We have to come up with another mechanism with update, though. Currently update are called for each frame rendering. This means that if your computer runs faster, then update will be called more frequently in same amount of time. However, I think update should be maintained at the same interval for similar performance across machines.

**Comment by xinyazhang** [comment]
```
You simply can't, due to the performance diversities b/w different
GPUs.

On 04/06/2015 05:47 PM, Tianyu Cheng
  wrote:


  We have to come up with another mechanism with update, though.
    Currently update are called for each frame rendering. This means
    that if your computer runs faster, then update will be called
    more frequently in same amount of time. However, I think update
    should be maintained at the same interval for similar
    performance across machines.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by xinyazhang** [comment]
I think I got your point of "similar performance". By fixing the FPS, we can fix the travel distance of camera for each frame, as well as other animations. Is that what you want?

However, this approach need extra efforts to ensure we are presenting each frame precisely.
As an example, if you want to present 60 frames in each second, you need to call Sleep(1) till you're almost reaching 1/60 sec, then you have to switch to busy waiting till it's 1/60 sec, after that you can present.
Such timing technique is troublesome and depends on the implementation of OS, which requires far more than what we want.

And more importantly, most games simply DO NOT TAKE THIS WAY (unfortunately touhou series are the few exceptions -- don't look into them).
For general cases, the animation is determined by time, not # of frames.
